# Generated by Django 5.1.6 on 2025-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UHID', models.CharField(max_length=50, unique=True, verbose_name='UHID')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pin_no', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('use_dob', models.BooleanField(default=False)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('age_days', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_date', models.DateField(blank=True, null=True)),
                ('policy_remark', models.TextField(blank=True, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital', models.CharField(max_length=255)),
                ('patient_type', models.CharField(choices=[('Self', 'Self'), ('Insurance', 'Insurance'), ('Corporate', 'Corporate')], default='Self', max_length=20)),
                ('tariff', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_company', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('doctor1', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor2', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=50)),
                ('patient_class', models.CharField(max_length=50)),
                ('prov_diagnosis', models.TextField(blank=True, null=True)),
                ('is_mlc', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('patient_status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
