# Generated by Django 5.1.6 on 2025-03-06 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_est_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicolegalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD')], max_length=3)),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('ip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('consultant_doctor', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('doa_date_time', models.DateTimeField()),
                ('accident_date', models.DateField()),
                ('accident_time', models.TimeField()),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('mlc_no', models.CharField(max_length=50, unique=True)),
                ('reporting_date_time', models.DateTimeField()),
                ('authority_name', models.CharField(max_length=255)),
                ('auth_buckle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('police_station', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(max_length=255)),
                ('admitted_doctor', models.CharField(max_length=255)),
                ('doctor_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_authority_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_auth_buckle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('details_of_injuries', models.TextField(blank=True, null=True)),
                ('age_of_injury', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_of_injury', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('New', 'New Patient'), ('Registered', 'Registered Patient')], default='New', max_length=10)),
                ('patient_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('admission_time', models.TimeField(default=django.utils.timezone.now)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('bed', models.CharField(blank=True, max_length=10, null=True)),
                ('cause_of_admission', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
