# Generated by Django 5.1.6 on 2025-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('taluka', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age_years', models.IntegerField(default=0)),
                ('age_months', models.IntegerField(default=0)),
                ('age_days', models.IntegerField(default=0)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_time', models.TimeField(auto_now_add=True)),
                ('hospital', models.CharField(max_length=200)),
                ('patient_type', models.CharField(max_length=50)),
                ('tariff', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('other_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('visit_flag', models.CharField(default='First Visit', max_length=100)),
                ('relative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode_cash', models.BooleanField(default=False)),
                ('bill_remark', models.TextField(blank=True, null=True)),
                ('warning', models.TextField(blank=True, null=True)),
                ('is_mlc', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_vip', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
            ],
        ),
    ]
