# Generated by Django 5.1.6 on 2025-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_expressregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('Area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age_years', models.IntegerField(default=0)),
                ('age_months', models.IntegerField(default=0)),
                ('age_days', models.IntegerField(default=0)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_no', models.CharField(max_length=15, unique=True)),
                ('warning', models.TextField(blank=True, null=True)),
                ('is_mlc', models.BooleanField(default=False)),
                ('occupation', models.CharField(max_length=50)),
                ('dependent', models.TextField(blank=True, null=True)),
                ('dep_occup', models.CharField(blank=True, max_length=10, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_time', models.TimeField(auto_now_add=True)),
                ('hospital', models.CharField(max_length=200)),
                ('patient_type', models.CharField(max_length=50)),
                ('tariff', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('ref_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('other_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
            ],
        ),
        migrations.RenameField(
            model_name='expressregistration',
            old_name='mobile_no',
            new_name='Phone_no',
        ),
    ]
