# Generated by Django 5.1.6 on 2025-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_regularregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularregistration',
            name='appointment_type',
            field=models.CharField(choices=[('Phone', 'Phone Appointment'), ('Walk-in', 'Walk-in Patient'), ('Mobile', 'Mobile App Appointment')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
