# Generated by Django 5.1.6 on 2025-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_medicalrecord_opdbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdbill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='opdbill',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='opdbill',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='opdbill',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opdbill',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opdbill',
            name='is_company_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdbill',
            name='patient_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opdbill',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
