# Generated by Django 5.1.6 on 2025-03-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('uhid', models.CharField(max_length=20, unique=True)),
                ('ip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('adm_dr', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
